services:
  lint:
    image: buildkite/plugin-linter
    command: [ '--id', 'datumforge/atlas' ]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"
