---
name: Atlas
description: Ariga Atlas Database Tool for use with atlasgo.io
author: Datum
requirements:
  - bash
  - curl
configuration:
  properties:
    dir: # The URL of the migration directory to push
      type: string
    project: # The name (slug) of the project in Atlas Cloud
      type: string
    dev-url:  # The URL of the dev-database to use for analysis
      type: string
    apply-env: # The environment to apply the migration to, defaults to turso
      type: string
    atlas-config: # The path to the atlas hcl config file, defaults to `file://atlas.hcl`
      type: string
    default-branch: # Default branch, defaults to `${BUILDKITE_PIPELINE_DEFAULT_BRANCH}`
      type: string
    step: # step to run, lint, migrate, push, all (runs all three). defaults to lint
      type: string
    debug: 
      type: string
  required:
    - dir
    - project
    - dev-url
  additionalProperties: false